### ISSUE TITLE
Highlight Gacha and Event Demons in Demon List

### ISSUE THREAD

**Issue by Maaster** [Alenael/Dx2WikiWriter#4]
* Highlight Gacha-only Demons in one color
* Event Demons in another

Not sure if the whole row or only the first cell... My first thought would be the cell is enough.

**Comment by Alenael** [comment]
Can you provide a sample of how this would look and colors you'd want to use?

**Comment by Maaster** [comment]
https://dx2wiki.com/index.php/Gacha_Demons_Example

Example. Colors not set in stone, but as we can easily put them as a variable its easily changable.

Do keep in touch with Sef though. He had the idea of using Icons - I have no idea how to style tables as good as him though, so at this point Im pretty much out I guess.

**Comment by Alenael** [comment]
This looks good once we have finalized the idea I can implement it in. I can provide a config form for colors if they need to be defined within the page themselves as well.

**Comment by Maaster** [comment]
Spoken with Sef again and he wants to edit the DemonIcon Template to include one variable more and show another icon to represent gacha/event only demons. Would say put this on hold for now, at least from the actual writing side.

In the end it would just mean every Demon String needs an additional argument passed into it
( https://github.com/Alenael/Dx2WikiWriter/blob/dddd4df921ec7e215c5a11711e54d9d7f374a1f7/Dx2WikiWriter/DemonHelper.cs#L359 )
to identify it as Gacha/event/whatever.

**Comment by Alenael** [comment]
I will do the pre work for now that adds this information to the database and writes it to the demons individual pages for now then as a category. To complete this issue though and prepare next release of wiki writer I will need a finalized example of what needs to be added to what pages.

**Comment by sethmccauley** [comment]
Check Discord for the updated process. And let me know if you have any questions!
