### ISSUE TITLE
Demon Summary

### ISSUE THREAD

**Issue by Maaster** [Alenael/Dx2WikiWriter#5]
* Add Demon Summary at top of Demon Page
* Write it to another subpage (/Summary ?), then include it via `{{:VisualEditor}}`, no Template needed.

Maybe add a link to /Builds in that summary.

**Comment by Alenael** [comment]
Can you provide a test sample of this in action to code against?

**Comment by Maaster** [comment]
What exactly do you need? A subpage and a demon page that pulls from that subpage as an example?

**Comment by Alenael** [comment]
* An example of {{:VisualEditor}} in action so I can code against how that should look.
* A sample /Summary page (If I need to be writing it from the database and this isn't a user editable item)

**Comment by Maaster** [comment]
See:
https://dx2wiki.com/index.php/Yoshitsune/Summary
https://dx2wiki.com/index.php/Yoshitsune

That VisualEditor thing was me forgetting to edit the name out. VisualEditor is the name of the article you wanna copy in. Sorry, it was late lol.

The Yoshi Summary Page is just taken from Azuraki and slightly altered with Bullet Points and 2 new points added, the latter being a link to the Builds section, in case users miss it.

**Comment by Alenael** [comment]
Alright I will update wiki writer to include `{{:DEMONNAME/Summary}}` before anything else. Other than this it would be nice to have a header and an edit button available in this page that takes you diretcly into editing summary page from the demons main page. Sef may be able to help get this setup as well which would give more potential for someone to update/change something they see as wrong or incomplete.
