### ISSUE TITLE
Indrajit wrong Nesting

### ISSUE THREAD

**Issue by Maaster** [Alenael/Dx2WikiWriter#6]
https://dx2wiki.com/index.php/Indrajit

It lists Lightning Shower as a child of Lord of Clouds. No clue why. Still shows fine, its just smaller font.

**Comment by Alenael** [comment]
Almost seems like an issue with either the Template:Demon page or with the info stored in the database which defiantly has a mistake in it. There is an extra / towards the end which may be triggering something in the wiki. 

Inflicts Elec (Magic) damage 5 times on a single enemy and 30% chance to inflict Bind on a single enemy. Power: 40\nLv2：+5% to damage dealt using this skill.\nLv3：+10% to damage dealt using this skill.\nLv4：+15% to damage dealt using this skill.\nLv5：+20% to damage dealt using this skill.\nLv6：+20% to damage dealt using this skill./MP cost of this skill -1.

**Comment by Alenael** [comment]
@Maaster After messing around a bit I noticed this affects any demon who has a move that starts with 'Adds Pierce. \n' because of he \n. I think you need to update the template to use <div> or something to help further separate each skill from one another in the nodes in order to resolve this across the entire Wiki.

**Comment by Maaster** [comment]
Yes, its definitely the \n in the skill  *before* the one that is then nested in. I dont know how to fix this via Template, seems to be a HTML/Mediawiki thing? As in: If theres a break, nest it one times lower.

I can look at it tomorrow again, but I doubt Ill find a fix. If Sef also doesnt have any ideas, how about we scrap all the normal linebreaks in skill descriptions as a dirty fix? :/ (Or we just leave it as is, I dont anyone is gonna actually see, let alone care.)

**Comment by Alenael** [comment]
> I dont know how to fix this via Template, seems to be a HTML/Mediawiki thing? As in: If theres a break, nest it one times lower.

I believe that WikiMedia accepts HTML right in templates. Could you try surrounding each Skill Innate with a Div or something and seeing if that helps separate the node enough that WikiMedia doesn't generate additional elements?

**Comment by Alenael** [comment]
The issue was resolved via div elements around each skill innate. This could also be moved to the skill template by adding div at the very beginning/end of the template.

**Comment by Alenael** [comment]
Issue is not completely fixed so re-opened this issue. Will continue to work on it until things look correct.

**Comment by Alenael** [comment]
I fixed this by adding some div's to the Template:Demon and applying an important css script.

`<div class='skill'> {{{MYSKILL}}}} </div>`

`.skill > span {
    font-size: 0.875em !important;
}`

To adjust the font size visit the URL below (If you cant change it I can) and update the em value for font-size. You will need to force a refresh of the sites cache locally as its a CSS change. 
https://dx2wiki.com/index.php/MediaWiki:Common.css

If this appears to solve the issue please close this out.
